### PR TITLE
Customize output name: round 2

### LINKED ISSUE #13: Add destination folder
As is, I couldn't find a way to add a destination folder, as docx-mailmerge requires a [ZipFile destination](https://github.com/Bouke/docx-mailmerge/blob/261bca9939b8660fadd0365461e3c7225fe2fd31/mailmerge.py#L126). A quick test showed that it doesn't bite on a given path. Hence, I suggest we post-processes the output, by - once it is generated - moving it to a specific subfolder. We can use [shutil](https://docs.python.org/3/library/shutil.html#shutil.move) for this. 

Actually, I would argue we create a 'result' folder by default to keep the directory clean (expecting more than 1 .docx to be created). We could add an argument if a different folder is preferred to be used.

Thoughts?

### PR DESCRIPTION
**Pull request by jawrainey**
Branched from @salmannotkhan's PR (#19) to not include the commits that change the file structure. I have added a new commit to improve and simplify the logic for accepting cell names to use for naming files. We should not commit this to master until testing is in place, but once resolved it will close #13.

### CODE REVIEW

**Comment by salmannotkhan** [comment]
About that src folder I tried to use csv2docx but because so many files/folders have same name(parent directory, library folder, module itself) it was creating some kind of confusion and I wasn't able to set csv2docx as source folder that's why I had to change name

**Comment by salmannotkhan** [comment]
About that sec folder I tried to use csv2docx but because so many files/folders have same name(parent directory, library folder, module itself) it was creating some kind of confusion and I wasn't able to set csv2docx as source folder that's why I had to change name

**Comment by salmannotkhan** [comment]
For that counter+1 I don't think end user will understand why file numbering starts at 0 instead of 1 that's why just for the sake of user understanding I did that

**Comment by salmannotkhan** [comment]
I'll try again tommorow to come up with better logic refactoring

**Comment by jawrainey** [comment]
> I'll try again tommorow to come up with better logic refactoring

I'd suggest that instead to read more on both [type annotations](https://github.com/davidverweij/csv2docx/issues/11) and [unit testing](https://github.com/davidverweij/csv2docx/pull/18#issuecomment-623629431) as that will be the main focus of this project in the coming weeks.

> I guessed this method take more time than seek() that's why I went with seek()

@salmannotkhan -- you're right that the proposed changes will take more time than `seek()` (since it reopens a file of unknown size), but efficiency opening large CSV files is unlikely going to be an issue. Using a separate method also means that we can test `unique_filenames()` in isolation whereas using `seek()` compounds the logic in `convert()`. Not currently an issue as the convert method is small, but as we add more features it will row in complexity -- making sure that does not happen early is important.  Of course, adding this new method introduces a new problem as now a user of the module could import and use the method -- likely something we do not want.

> For that counter+1 I don't think end user will understand why file numbering starts at 0 instead of 1 that's why just for the sake of user understanding I did that

Great point. I also think that outputting files based on a counter by default is probably not the best approach ... maybe we could instead force the user to choose a field they want to use as the output names by making `column_name ` a _required_ parameter? What do you think @davidverweij?

**Comment by salmannotkhan** [comment]
I thought of a new idea what if we save that csvdict into another temporary variable and then use my method on that temporary variable??

**Comment by salmannotkhan** [comment]
What if we check the directory for the file and if the file exists we append filename with counter and avoid creating the filename list in advance

**Comment by salmannotkhan** [comment]
Here is what i come up with:
`from glob import glob

def generate_name(filename):
    fullpath = "./" + filename + ".docx"
    filelist = glob("./" + filename + "*.docx")
    if fullpath in filelist:
        return f"{filename}_{len(filelist) + 1}.docx"
    return fullpath`

we can pass this return as name for write function

**Comment by jawrainey** [comment]
> What if we check the directory for the file and if the file exists we append filename with counter and avoid creating the filename list in advance

I am not sure what you mean as the _output file_ does not exist before running csv2docx, so there is no 'filename' from which we can `generate_name`. Creating the filename list in advance ([see here](https://github.com/davidverweij/csv2docx/pull/20/files#diff-943d1d6d09f3f957ed3d46fd8acede0bR6-R23)) only occurs if `column_name` was provided as there's no way we can know what the user wants to call the output files. An alternative would be to use sensible defaults, but given we accept any `.csv` that may have diverse ranges of column names, then this is not possible.

My comment above was that instead of using a counter by default (e.g. 0-N.docx), we should make column _required_ by default so the user has to define a filename. This way the user will _always_ have output files that make sense to them.

**Comment by salmannotkhan** [comment]
> I am not sure what you mean as the output file does not exist before running csv2docx
what if user is running the script again with another .csv file that contains same name from previous csv file. I'm talking about that case

i took care of that issue also check my PR #22  if that's any good

**Comment by jawrainey** [comment]
This PR has been supplanted by #22

**Pull request closed without merging**
